apiVersion: v1 
kind: Pod              
metadata:              
  name: liveness-tcp-pod      
  namespace: default    
  labels:                   
    app: liveness-tcp-pod  
    release: beta
spec:           
  containers:            
  - name: liveness-tcp-container       
    image: yeasy/simple-web:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 1
        periodSeconds: 3
