apiVersion: v1 
kind: Pod              
metadata:              
  name: readiness-httpget-pod      
  namespace: default    
  labels:                   
    app: readiness-httpget-pod
    release: beta
spec:           
  containers:            
  - name: readiness-httpget-container       
    image: yeasy/simple-web:latest
    imagePullPolicy: IfNotPresent
    readinessProbe:
        httpGet:
            port: 80
            path: /index.html
        initialDelaySeconds: 1
        periodSeconds: 3
