apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewogICJhdXRocyIgOiB7CiAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIiA6IHsKCiAgICB9CiAgfSwKICAiY3JlZFNzdG9yZSIgOiAib3N4a2V5Y2hhaW4iLAogICJzdGFja09yY2hlc3RyYXRvciIgOiAic3dhcm0iCn0KCg==