apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: foo
      image: busybox
      command: ['sh', '-c', 'echo The app is running!']
  imagePullSecrets:
    - name: myregistrykey