apiVersion: v1
kind: Service
metadata:
  name: goapp-svc
  namespace: default
  labels:
    k8s-app: goappk8s
spec:
  type: NodePort
  ports:
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    k8s-app: goappk8s