---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: goapp-deploy
    namespace: default
    labels:
      k8s-app: goappk8s
spec:
  replicas: 2
  revisionHistoryLimit: 10
  minReadySeconds: 5
  selector:
    matchLabels:
      k8s-app: goappk8s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: goappk8s
    spec:
      containers:
        - image: leasy/demo-api-go:v1
          imagePullPolicy: Always
          name: demo-api-go
          ports:
          - containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 10
            timeoutSeconds: 2
    
---
apiVersion: v1
kind: Service
metadata:
  name: goapp-svc
  namespace: default
  labels:
    k8s-app: goappk8s
spec:
  ports:
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    k8s-app: goappk8s
    
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: goapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: default
spec:
  rules:
  - host: goappk8s.local
    http:
      paths:
      - path: /
        backend:
          serviceName: goapp-svc
          servicePort: api