apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-api-replica-set
spec:
  selector:
    matchLabels:
      app: demo-api-rs
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-api-rs
    spec:
      containers:
      - name: demo-api-container
        image: leasy/demo-api:v2
        command: ["/demo-api/start.sh"]
        ports:
        - containerPort: 8080